name: docy
description: "A new Flutter project for storing documents, notes, and important files."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  velocity_x: ^3.3.0  
  getwidget: ^2.0.4
  file_picker: ^8.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  email_validator: ^3.0.0
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.4
  permission_handler: ^11.3.1
  url_launcher: ^6.0.20 
  riverpod: ^2.5.3 # Keep if using standalone
  flutter_riverpod: ^2.5.3 # Only if necessary
  open_file: ^3.5.9
  dio: ^5.7.0
  path_provider: ^2.1.4
  flutter_document_scanner: ^1.1.2
  flutter_screenutil: ^5.9.3
  image_cropper: ^8.0.2
  flutter_launcher_icons: ^0.14.1
  email_otp: ^3.0.2
  http: ^1.2.2
  lottie: ^3.1.3
  salomon_bottom_bar: ^3.3.2
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/assets/lottie/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "D:/docy/docy/lib/assets/icons/app_icon.png" 
